# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-15 20:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bird',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Common_Name', models.CharField(max_length=100, unique=True)),
                ('Species_Name', models.CharField(max_length=100, unique=True)),
                ('Short_Description', models.TextField()),
                ('Image_Ref', models.ImageField(upload_to=b'')),
                ('Sound_Ref', models.FileField(upload_to=b'')),
                ('Diet', models.TextField()),
                ('Sleeping_Habits', models.CharField(max_length=35)),
                ('Habitat', models.TextField()),
            ],
            options={
                'ordering': ('Common_Name',),
            },
        ),
    ]
