# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-15 20:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bird',
            name='Diet',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bird',
            name='Habitat',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bird',
            name='Image_Ref',
            field=models.ImageField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='bird',
            name='Sleeping_Habits',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='bird',
            name='Sound_Ref',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
    ]
