# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 17:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0002_auto_20170415_2054'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bird',
            options={'ordering': ('Name',)},
        ),
        migrations.RenameField(
            model_name='bird',
            old_name='Short_Description',
            new_name='Description',
        ),
        migrations.RenameField(
            model_name='bird',
            old_name='Image_Ref',
            new_name='Image',
        ),
        migrations.RenameField(
            model_name='bird',
            old_name='Common_Name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='bird',
            old_name='Sleeping_Habits',
            new_name='Sleep',
        ),
        migrations.RenameField(
            model_name='bird',
            old_name='Sound_Ref',
            new_name='Sound',
        ),
        migrations.RenameField(
            model_name='bird',
            old_name='Species_Name',
            new_name='Species',
        ),
    ]
