# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-09 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0003_auto_20170421_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='bird',
            name='Slug',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bird',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='bird',
            name='Sound',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
